services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - mailcatcher
      - elasticsearch
    volumes:
      - .:/usr/src/app
    command:
      - /bin/bash
      - -c
      - |
          rails db:setup
          rails s -b 0.0.0.0

  db:
    image: postgres:14.1
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5442:5432"

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - transport.host=localhost
      - bootstrap.system_call_filter=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  db_data:
  elasticsearch_data: